const i18Obj = {
  en: {
    about_psyho: "About psychology",
    about_me: "About me",
    reviews: "Reviews",
    contacts: "Contacts",
    contract: "Contract",
    "mobile-menu-text": "Site language",
    "main-offline-online": "Offline and online consultations",
    "main-fio": "Valeriya Kryzhanovskaya",
    "main-text":
      "I am a practicing psychologist-sexologist, working in psychoanalytic and symbol-dramatic approaches.",
    "btn-text": "Schedule a consultation",
    "about-psyho-title": "How does psychotherapy work?",
    "about-psyho-text1":
      "Psychotherapy (from the Greek words psyche - soul, and therapy - treatment) is a healing process that influences the human psyche to improve their mental and physical condition.",
    "about-psyho-text2":
      'The principle of my work is based on the methods of psychoanalysis and catathymic-imaginative psychotherapy (symboldrama or the catathymic experience of images). Psychoanalytic therapy involves analyzing the patient\'s free associations. Catathymic Imagery Facilitation (CIF) is a depth-psychologically oriented psychotherapy method, also known as the "waking dream" method.',
    "about-psyho-text3":
      "During therapy, the patient discusses what bothers him, including thoughts, images, objects, etc. In this process, the psychotherapist assists in uncovering the hidden meanings or patterns within these associations. This exploration can provide insight into the presence of psychological problems and facilitate their resolution.",
    "about-me-title": "About me",
    "about-me-subtitle":
      "Practicing psychologist-sexologist in the psychoanalytic approach.",
    "about-me-item1":
      "Graduated from Odessa National University named after I.I. Mechnikov, with a Master's degree in Psychology.",
    "about-me-item2":
      "Candidate psychotherapist using the method of symboldrama (catathymic-imaginative psychotherapy).",
    "about-me-item3":
      "Member of the Ukrainian Union of Psychotherapists (UUP).",
    "about-me-item4":
      'Current member of the Ukrainian public organization "Institute for the Development of Symbols and Mental Psychology" (UGO IRSGP).',
    "about-me-item5": "Odessa Institute of Psychoanalysis",
    "about-me-item6": 'Clinical Psychology. Psychodiagnostics at KU "OOMCPZ".',
    "about-me-item7":
      'Organic Personality Disorders. BAR. Psychoses at KU "OOMCPZ".',
    "about-me-item8": 'Schizophrenia at KU "OOMCPZ".',
    "about-me-item9": 'Suicidology at KU "OOMCPZ".',
    "about-me-item10": 'Neuroses at KU "OOMCPZ".',
    "about-me-item11":
      "Propaedeutics of Psychiatry at the Ukrainian Union of Psychotherapists (USP).",
    "how-works-title": "What does a psychotherapist work with?",
    "how-works-subtitle": "The main directions of a psychotherapist's work",
    "how-works-direction1-title": "Relationships in a couple",
    "how-works-direction1-item1": "Getting through a breakup",
    "how-works-direction1-item2": "Dissatisfaction with relationships",
    "how-works-direction2-title": "Family",
    "how-works-direction2-item1": "Marital relationships",
    "how-works-direction2-item2": "Conflicts with a child",
    "how-works-direction2-item3": "Parenting issues",
    "how-works-direction2-item4": "Relationship crises",
    "how-works-direction3-title": "How to change your life?",
    "how-works-direction3-item1": "Exploring psychological barriers to change",
    "how-works-direction4-title": "Difficult life choice",
    "how-works-direction4-item1": "Crisis and the issue of self-definition",
    "how-works-direction4-item2": "Ambivalence",
    "how-works-direction5-title": "Personal development",
    "how-works-direction5-item1": "Age-related crises",
    "how-works-direction5-item2": "Improving quality of life",
    "how-works-direction6-title": "Self-esteem",
    "how-works-direction6-item1": "Confidence in oneself and one's actions",
    "how-works-direction6-item2": "Self-discovery",
    "how-works-direction7-title": "Psychological support",
    "how-works-direction7-item1": "Sudden life changes",
    "how-works-direction7-item2": "The move to another country",
    "how-works-direction8-title": "Working with emotional states",
    "how-works-direction8-item1": "Desperation, confusion",
    "how-works-direction8-item2": "Panic attacks, anxiety, fears, depression",
    "education-title": "Education",
    "experience-text1": "Hours of Practice",
    "experience-text2": "Hours of Supervision",
    "experience-text3": "Personal therapy",
    "experience-text4": "Reviews",
    "reviews-title": "Reviews",
    "footer-location": "Odessa, 63 Bazarnaya str.",
    "footer-days": "Monday - Friday",
  },
  ru: {
    about_psyho: "О психологии",
    about_me: "Обо мне",
    reviews: "Отзывы",
    contacts: "Контакты",
    contract: "Договор",
    "mobile-menu-text": "Язык сайта",
    "main-offline-online": "оффлайн и онлайн консультации",
    "main-fio": "Валерия Крыжановская",
    "main-text":
      "Я практикующий психолог-сексолог, работаю в психоаналитическом и символдраматическом подходах.",
    "btn-text": "Записаться на консультацию",
    "about-psyho-title": "Как проходит психотерапия?",
    "about-psyho-text1":
      "Психотерапия (от греч. психе — душа, терапия — лечение) – это лечебный процесс, по средствам воздействия на психику человека с целью улучшения его психического и физического состояния.",
    "about-psyho-text2":
      'Принцип моей работы основан на методе психоанализа и кататимно-имагинативной психотерапии (символдрама или кататимное переживание образов). Психоаналитическая терапия основана на анализе свободных ассоциаций пациента. Кататимное переживания образов (КПО) - это метод глубинно-психологически ориентированной психотерапии, известный также как метод "сновидений наяву".',
    "about-psyho-text3":
      "В процессе терапии пациент рассказывает о том что его беспокоит, с помощью свободных ассоциаций (мысли, образы, предметы и т.д.). В этот случае психотерапевт помогает осознать скрытые значения или закономерности этих ассоциаций, это может послужить основной для нахождения психологических проблем, для последующих их решений.",
    "about-me-title": "Обо мне",
    "about-me-subtitle":
      "Практикующий психолог-сексолог в психоаналитическом подходе. ",
    "about-me-item1":
      "Закончила Одесский Национальный Университет  им. И.И. Мечникова, Магистр психологии",
    "about-me-item2":
      "Кандидат в психотерапевты по методу символдрама (кататимно-иммагинативная психотерапия)",
    "about-me-item3": "Член Украинского Союза Психотерапевтов (УСП)",
    "about-me-item4":
      'Действующий член Украинской общественной организации "Інститут розвитку символдрами та глибинної психології" (УГО ІРСГП)',
    "about-me-item5": "Одесский институт психоанализа",
    "about-me-item6":
      'Клиническая психология. Психодиагностика при КУ "ООМЦПЗ"',
    "about-me-item7":
      'Органические расстройства личности. БАР. Психозы при КУ "ООМЦПЗ"',
    "about-me-item8": 'Шизофрения при КУ "ООМЦПЗ"',
    "about-me-item9": 'Суицидология при КУ "ООМЦПЗ"',
    "about-me-item10": 'Неврозы при КУ "ООМЦПЗ"',
    "about-me-item11":
      "Пропедевтика психиатрии при Украинском Союзе Психотерапевтов (УСП)",
    "how-works-title": "С чем работает психотерапевт?",
    "how-works-subtitle": "Основные направления работы психотерапевта",
    "how-works-direction1-title": "ОТНОШЕНИЯ В ПАРЕ",
    "how-works-direction1-item1": "Пережить расставание",
    "how-works-direction1-item2": "Неудовлетворенность отношениями",
    "how-works-direction2-title": "СЕМЬЯ",
    "how-works-direction2-item1": "Супружеские отношения",
    "how-works-direction2-item2": "Конфликты с ребенком",
    "how-works-direction2-item3": "Вопросы воспитания",
    "how-works-direction2-item4": "Кризисы в отношениях",
    "how-works-direction3-title": "КАК ИЗМЕНИТЬ СВОЮ ЖИЗНЬ?",
    "how-works-direction3-item1":
      "Исследование психологических «препятствий» к изменениям",
    "how-works-direction4-title": "СЛОЖНЫЙ ЖИЗНЕННЫЙ ВЫБОР",
    "how-works-direction4-item1": "Кризис и проблема самоопределения",
    "how-works-direction4-item2": "Амбивалентность",
    "how-works-direction5-title": "ЛИЧНОСТНОЕ РАЗВИТИЕ",
    "how-works-direction5-item1": "Возрастные кризисы",
    "how-works-direction5-item2": "Улучшение качества жизни",
    "how-works-direction6-title": "ОТНОШЕНИЕ К СЕБЕ",
    "how-works-direction6-item1": "Уверенность в себе и своих действиях",
    "how-works-direction6-item2": "Поиск себя",
    "how-works-direction7-title": "ПСИХОЛОГИЧЕСКОЕ СОПРОВОЖДЕНИЕ",
    "how-works-direction7-item1": "Резкое изменение условий жизни",
    "how-works-direction7-item2": "Переезд в другую страну",
    "how-works-direction8-title": "РАБОТА С ЭМОЦИОНАЛЬНЫМИ СОСТОЯНИЯМИ",
    "how-works-direction8-item1": "Отчаяние, растерянность",
    "how-works-direction8-item2":
      "Панические атаки, тревога, страхи, депрессии",
    "education-title": "Образование",
    "experience-text1": "Часов практики",
    "experience-text2": "Часов супервизий",
    "experience-text3": "Личной терапии",
    "experience-text4": "Отзывов",
    "reviews-title": "Отзывы",
    "footer-location": "г.Одесса, ул.Базарня 63",
    "footer-days": "Понeдельник - Пятница",
  },
  ua: {
    about_psyho: "Про психологію",
    about_me: "Про мене",
    reviews: "Відгуки",
    contacts: "Контакти",
    contract: "Договір",
    "mobile-menu-text": "Мова сайту",
    "main-offline-online": "Офлайн та онлайн консультації",
    "main-fio": "Валерія Крижановська",
    "main-text":
      "Я практикуючий психолог-сексолог, працюю в психоаналітичному та символдраматичному підходах.",
    "btn-text": "Записатися на консультацію",
    "about-psyho-title": "Як проходить психотерапія? ",
    "about-psyho-text1":
      "Психотерапія (від грецького психе — душа, терапія — лікування) — це лікувальний процес, який впливає на психіку людини з метою поліпшення її психічного і фізичного стану.",
    "about-psyho-text2":
      'Принцип моєї роботи ґрунтується на методі психоаналізу і кататимно-імагінативній психотерапії (символдрама або кататимне переживання образів). Психоаналітична терапія ґрунтується на аналізі вільних асоціацій пацієнта. Кататимне переживання образів (КПО) — це метод глибинно-психологічно орієнтованої психотерапії, також відомий як метод "сновидінь наяву".',
    "about-psyho-text3":
      "Під час терапії пацієнт розповідає про те, що турбує його, використовуючи вільні асоціації (думки, образи, предмети і т.д.). У цьому випадку психотерапевт допомагає усвідомити приховані значення або закономірності цих асоціацій, що може стати основою для виявлення психологічних проблем і їх подальшого вирішення.",
    "about-me-title": "Про мене",
    "about-me-subtitle":
      "Практикуючий психолог-сексолог з психоаналітичним підходом.",
    "about-me-item1":
      "Закінчила Одеський національний університет імені І.І. Мечникова, магістр психології.",
    "about-me-item2":
      "Кандидат у психотерапевти з методу символдрама (кататимно-імагінативна психотерапія).",
    "about-me-item3": "Член Українського Союзу Психотерапевтів (УСП).",
    "about-me-item4":
      'Діючий член Української громадської організації "Інститут розвитку символдрами та глибинної психології" (УГО ІРСГП).',
    "about-me-item5": "Одеський інститут психоаналізу",
    "about-me-item6": 'Клінічна психологія. Психодіагностика в КУ "ООМЦПЗ"',
    "about-me-item7":
      'Органічні розлади особистості. БАР. Психози в КУ "ООМЦПЗ"',
    "about-me-item8": 'Шизофренія в КУ "ООМЦПЗ"',
    "about-me-item9": 'Суїцидологія в КУ "ООМЦПЗ"',
    "about-me-item10": 'Неврози в КУ "ООМЦПЗ"',
    "about-me-item11":
      "Пропедевтика психіатрії в Українському Союзі Психотерапевтів (УСП).",
    "how-works-title": "Із чим працює психотерапевт?",
    "how-works-subtitle": "Основні напрямки роботи психотерапевта",
    "how-works-direction1-title": "ВІДНОСИНИ У ПАРІ",
    "how-works-direction1-item1": "Пережити розлучення",
    "how-works-direction1-item2": "Незадоволеність відносинами",
    "how-works-direction2-title": "РОДИНА",
    "how-works-direction2-item1": "Подружні стосунки",
    "how-works-direction2-item2": "Конфлікти з дитиною",
    "how-works-direction2-item3": "Питання виховання",
    "how-works-direction2-item4": "Кризи у відносинах",
    "how-works-direction3-title": "ЯК ЗМІНИТИ СВОЄ ЖИТТЯ?",
    "how-works-direction3-item1":
      "Дослідження психологічних «перешкод» до змін",
    "how-works-direction4-title": "СКЛАДНИЙ ЖИТТЯНИЙ ВИБІР",
    "how-works-direction4-item1": "Криза та проблема самовизначення",
    "how-works-direction4-item2": "Амбівалентність",
    "how-works-direction5-title": "ОСОБИСТІСНИЙ РОЗВИТОК",
    "how-works-direction5-item1": "Вікові кризи",
    "how-works-direction5-item2": "Поліпшення якості життя",
    "how-works-direction6-title": "СТАВЛЕННЯ ДО СЕБЕ",
    "how-works-direction6-item1": "Впевненість у собі та своїх діях",
    "how-works-direction6-item2": "Пошук себе",
    "how-works-direction7-title": "ПСИХОЛОГІЧНИЙ СУПРОВІД",
    "how-works-direction7-item1": "Різка зміна умов життя",
    "how-works-direction7-item2": "Переїзд в іншу країну",
    "how-works-direction8-title": "РОБОТА З ЕМОЦІЙНИМИ СТАНАМИ",
    "how-works-direction8-item1": "Розпач, розгубленість",
    "how-works-direction8-item2": "Панічні атаки, тривога, страхи, депресії",
    "education-title": "Освіта",
    "experience-text1": "Годин практики",
    "experience-text2": "Годин супервізій",
    "experience-text3": "Особистої терапії",
    "experience-text4": "Відгуків",
    "reviews-title": "Відгуки",
    "footer-location": "м.Одеса, вул.Базарна 63",
    "footer-days": "Понеділок - П'ятниця",
  },
};

export default i18Obj;
